name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Scoop
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
          Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\scoop\shims"
      - name: Validate manifests
        shell: pwsh
        run: |
          foreach ($manifest in Get-ChildItem bucket -Filter *.json) {
            scoop info $manifest.FullName
          }
